/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and DB connectivity */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Sample Dataset */
        post: operations["load_sample_dataset_api_v1_datasets_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_v1_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_datasets__dataset_id__profile_patch"];
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quality */
        get: operations["get_quality_api_v1_datasets__dataset_id__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/eda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eda */
        get: operations["get_eda_api_v1_datasets__dataset_id__eda_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calibration */
        get: operations["get_calibration_api_v1_runs__run_id__calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/importance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Importance */
        get: operations["get_importance_api_v1_runs__run_id__importance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Customer */
        post: operations["explain_customer_api_v1_runs__run_id__explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/single": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Single */
        post: operations["score_single_api_v1_predictions_single_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_v1_predictions_batch_get"];
        put?: never;
        /** Score Batch */
        post: operations["score_batch_api_v1_predictions_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/batch/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_v1_predictions_batch__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/batch/{batch_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batch Items */
        get: operations["list_batch_items_api_v1_predictions_batch__batch_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions/{prediction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction */
        get: operations["get_prediction_api_v1_predictions__prediction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssumptionsBlock
         * @description Shipped with every financial payload so no figure is ever shown without its basis.
         */
        AssumptionsBlock: {
            /** Save Rate */
            save_rate: number;
            /** Gross Margin */
            gross_margin: number;
            /** Discount Rate Monthly */
            discount_rate_monthly: number;
            /** Horizon Months */
            horizon_months: number;
        };
        /** BatchSummary */
        BatchSummary: {
            /** N Scored */
            n_scored: number;
            /** Tier Counts */
            tier_counts: {
                [key: string]: number;
            };
            /** Mean Churn Probability */
            mean_churn_probability: number;
            /** Total Monthly Revenue At Risk */
            total_monthly_revenue_at_risk: number;
            /** Total Annual Revenue At Risk */
            total_annual_revenue_at_risk: number;
            /** Total Expected Value At Risk */
            total_expected_value_at_risk: number;
            /** Total Expected Saved */
            total_expected_saved: number;
            /** Total Campaign Cost */
            total_campaign_cost: number;
            assumptions: components["schemas"]["AssumptionsBlock"];
        };
        /** Body_score_batch_api_v1_predictions_batch_post */
        Body_score_batch_api_v1_predictions_batch_post: {
            /** Run Id */
            run_id: string;
            /** File */
            file: string;
        };
        /** Body_upload_dataset_api_v1_datasets_post */
        Body_upload_dataset_api_v1_datasets_post: {
            /** File */
            file: string;
        };
        /** CalibrationCurve */
        CalibrationCurve: {
            /** Points */
            points: components["schemas"]["CalibrationPoint"][];
        };
        /** CalibrationPoint */
        CalibrationPoint: {
            /** Predicted */
            predicted: number;
            /** Observed */
            observed: number;
            /** Count */
            count: number;
        };
        /** CategoricalSummary */
        CategoricalSummary: {
            /** Column */
            column: string;
            /** Levels */
            levels: string[];
            /** Counts */
            counts: number[];
            /** Churn Rate */
            churn_rate: number[];
        };
        /** ClassBalance */
        ClassBalance: {
            /** Positive */
            positive: number;
            /** Negative */
            negative: number;
            /** Positive Rate */
            positive_rate: number;
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** Id Column */
            id_column: string | null;
            /** Target Column */
            target_column: string;
            /** Revenue Column */
            revenue_column: string;
            /** Tenure Column */
            tenure_column: string | null;
            /** Numeric */
            numeric: string[];
            /** Categorical Low */
            categorical_low: string[];
            /** Categorical High */
            categorical_high: string[];
            /** Dropped */
            dropped: string[];
        };
        /**
         * ColumnProfileUpdate
         * @description PATCH body — every field optional, only supplied ones are overridden.
         */
        ColumnProfileUpdate: {
            /** Id Column */
            id_column?: string | null;
            /** Target Column */
            target_column?: string | null;
            /** Revenue Column */
            revenue_column?: string | null;
            /** Tenure Column */
            tenure_column?: string | null;
            /** Numeric */
            numeric?: string[] | null;
            /** Categorical Low */
            categorical_low?: string[] | null;
            /** Categorical High */
            categorical_high?: string[] | null;
            /** Dropped */
            dropped?: string[] | null;
        };
        /** Correlation */
        Correlation: {
            /** Columns */
            columns: string[];
            /** Matrix */
            matrix: number[][];
        };
        /**
         * CustomerFinancials
         * @description Money attached to one customer's churn probability, per DATA_CONTRACT.md.
         */
        CustomerFinancials: {
            /** Arpu */
            arpu: number;
            /** Clv */
            clv: number;
            /** Monthly Revenue At Risk */
            monthly_revenue_at_risk: number;
            /** Annual Revenue At Risk */
            annual_revenue_at_risk: number;
            /** Expected Value At Risk */
            expected_value_at_risk: number;
            /** Expected Saved */
            expected_saved: number;
            /** Campaign Cost */
            campaign_cost: number;
            /** Roi */
            roi: number | null;
            assumptions: components["schemas"]["AssumptionsBlock"];
        };
        /** Dataset */
        Dataset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
            column_profile: components["schemas"]["ColumnProfile"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EDAPayload */
        EDAPayload: {
            /** Histograms */
            histograms: components["schemas"]["Histogram"][];
            /** Categorical */
            categorical: components["schemas"]["CategoricalSummary"][];
            correlation: components["schemas"]["Correlation"];
            target_distribution: components["schemas"]["TargetDistribution"];
            /** Missing Matrix */
            missing_matrix: components["schemas"]["MissingColumn"][];
        };
        /** ExplainRequest */
        ExplainRequest: {
            /** Features */
            features: {
                [key: string]: unknown;
            };
        };
        /** Explanation */
        Explanation: {
            /** Run Id */
            run_id: string;
            /** Algorithm */
            algorithm: string;
            /** Churn Probability */
            churn_probability: number;
            /** Base Value */
            base_value: number;
            /**
             * Output Space
             * @enum {string}
             */
            output_space: "logit" | "probability";
            /** Shap Values */
            shap_values: components["schemas"]["FeatureContribution"][];
        };
        /**
         * FeatureContribution
         * @description One source column's push on a single customer's score, per DATA_CONTRACT.md.
         */
        FeatureContribution: {
            /** Feature */
            feature: string;
            /** Display Name */
            display_name: string;
            /** Value */
            value: number | string | null;
            /** Contribution */
            contribution: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "increases_risk" | "decreases_risk";
        };
        /**
         * GlobalImportance
         * @description Mean |SHAP| per source column over a validation sample, computed once at training time.
         */
        GlobalImportance: {
            /** Features */
            features: components["schemas"]["ImportanceFeature"][];
            /** Sample Size */
            sample_size: number;
            /**
             * Output Space
             * @enum {string}
             */
            output_space: "logit" | "probability";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error";
        };
        /** Histogram */
        Histogram: {
            /** Column */
            column: string;
            /** Bins */
            bins: number[];
            /** Counts */
            counts: number[];
        };
        /** ImportanceFeature */
        ImportanceFeature: {
            /** Feature */
            feature: string;
            /** Display Name */
            display_name: string;
            /** Importance */
            importance: number;
        };
        /** LeakageWarning */
        LeakageWarning: {
            /** Column */
            column: string;
            /** Reason */
            reason: string;
            /** Score */
            score: number;
        };
        /** MissingColumn */
        MissingColumn: {
            /** Column */
            column: string;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /** ModelArtifactOut */
        ModelArtifactOut: {
            /** Id */
            id: string;
            /** Algorithm */
            algorithm: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            metrics: components["schemas"]["ModelMetricsBySplit"];
            /** Is Best */
            is_best: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelMetrics */
        ModelMetrics: {
            /** Accuracy */
            accuracy: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** F1 */
            f1: number;
            /** Roc Auc */
            roc_auc: number;
            /** Pr Auc */
            pr_auc: number;
            /** Brier */
            brier: number;
            /** Confusion Matrix */
            confusion_matrix: number[][];
            /**
             * Split
             * @enum {string}
             */
            split: "validation" | "test";
        };
        /** ModelMetricsBySplit */
        ModelMetricsBySplit: {
            validation: components["schemas"]["ModelMetrics"];
            test?: components["schemas"]["ModelMetrics"] | null;
        };
        /** Outlier */
        Outlier: {
            /** Column */
            column: string;
            /** Method */
            method: string;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /** Page[Dataset] */
        Page_Dataset_: {
            /** Items */
            items: components["schemas"]["Dataset"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[PredictionBatch] */
        Page_PredictionBatch_: {
            /** Items */
            items: components["schemas"]["PredictionBatch"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[PredictionListItem] */
        Page_PredictionListItem_: {
            /** Items */
            items: components["schemas"]["PredictionListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Run] */
        Page_Run_: {
            /** Items */
            items: components["schemas"]["Run"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Prediction */
        Prediction: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Run Id */
            run_id: string;
            /** Customer Ref */
            customer_ref: string | null;
            /** Features */
            features: {
                [key: string]: unknown;
            };
            /** Churn Probability */
            churn_probability: number;
            /**
             * Risk Tier
             * @enum {string}
             */
            risk_tier: "low" | "medium" | "high" | "critical";
            shap_values: components["schemas"]["PredictionShap"];
            financials: components["schemas"]["CustomerFinancials"];
            /** Segment Label */
            segment_label: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PredictionBatch */
        PredictionBatch: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "single" | "csv";
            /** Filename */
            filename: string | null;
            /** N Rows */
            n_rows: number;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            summary?: components["schemas"]["BatchSummary"] | null;
        };
        /**
         * PredictionListItem
         * @description The customer list's row — everything it renders, and nothing it doesn't.
         *
         *     SHAP and the full feature dict are deliberately absent: a thousand-row page carrying every
         *     customer's contributions is megabytes of payload nobody looks at until a row is opened.
         */
        PredictionListItem: {
            /** Id */
            id: string;
            /** Customer Ref */
            customer_ref: string | null;
            /** Churn Probability */
            churn_probability: number;
            /**
             * Risk Tier
             * @enum {string}
             */
            risk_tier: "low" | "medium" | "high" | "critical";
            /** Segment Label */
            segment_label: string | null;
            /** Arpu */
            arpu: number;
            /** Monthly Revenue At Risk */
            monthly_revenue_at_risk: number;
            /** Expected Value At Risk */
            expected_value_at_risk: number;
            /** Expected Saved */
            expected_saved: number;
            /** Campaign Cost */
            campaign_cost: number;
            /** Roi */
            roi: number | null;
        };
        /**
         * PredictionShap
         * @description SHAP for one customer, aggregated to source columns and sorted by |contribution|.
         */
        PredictionShap: {
            /** Base Value */
            base_value: number;
            /**
             * Output Space
             * @enum {string}
             */
            output_space: "logit" | "probability";
            /** Values */
            values: components["schemas"]["FeatureContribution"][];
        };
        /** QualityReport */
        QualityReport: {
            /** N Rows */
            n_rows: number;
            /** N Duplicate Rows */
            n_duplicate_rows: number;
            /** Missing */
            missing: components["schemas"]["MissingColumn"][];
            /** Type Issues */
            type_issues: components["schemas"]["TypeIssue"][];
            /** Outliers */
            outliers: components["schemas"]["Outlier"][];
            class_balance: components["schemas"]["ClassBalance"];
            /** Leakage Warnings */
            leakage_warnings: components["schemas"]["LeakageWarning"][];
            /** Warnings */
            warnings: string[];
            /** Blocking Errors */
            blocking_errors: string[];
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Dataset Id */
            dataset_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            config: components["schemas"]["RunConfig"];
            /** Best Model Id */
            best_model_id: string | null;
            /** Chosen Threshold */
            chosen_threshold: number | null;
            /** Risk Tier Bounds */
            risk_tier_bounds: {
                [key: string]: number[];
            } | null;
            global_importance: components["schemas"]["GlobalImportance"] | null;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Models */
            models: components["schemas"]["ModelArtifactOut"][];
        };
        /** RunConfig */
        RunConfig: {
            /** Algorithms */
            algorithms: string[];
            /** Tune */
            tune: boolean;
        };
        /** RunCreate */
        RunCreate: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * Algorithms
             * @default [
             *       "logistic_regression",
             *       "random_forest",
             *       "xgboost",
             *       "lightgbm"
             *     ]
             */
            algorithms: string[];
            /**
             * Tune
             * @default false
             */
            tune: boolean;
        };
        /** SinglePredictionRequest */
        SinglePredictionRequest: {
            /** Run Id */
            run_id: string;
            /** Features */
            features: {
                [key: string]: unknown;
            };
        };
        /** TargetDistribution */
        TargetDistribution: {
            /** Labels */
            labels: string[];
            /** Counts */
            counts: number[];
        };
        /** TypeIssue */
        TypeIssue: {
            /** Column */
            column: string;
            /** Expected */
            expected: string;
            /** Found */
            found: string;
            /** N Bad */
            n_bad: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Dataset_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_sample_dataset_api_v1_datasets_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_v1_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_v1_datasets__dataset_id__profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_api_v1_datasets__dataset_id__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eda_api_v1_datasets__dataset_id__eda_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EDAPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Run_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calibration_api_v1_runs__run_id__calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationCurve"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_importance_api_v1_runs__run_id__importance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalImportance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_customer_api_v1_runs__run_id__explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_single_api_v1_predictions_single_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SinglePredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_predictions_batch_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PredictionBatch_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_batch_api_v1_predictions_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_score_batch_api_v1_predictions_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_v1_predictions_batch__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batch_items_api_v1_predictions_batch__batch_id__items_get: {
        parameters: {
            query?: {
                risk_tier?: ("low" | "medium" | "high" | "critical") | null;
                segment?: string | null;
                sort?: "expected_value_at_risk" | "churn_probability" | "monthly_revenue_at_risk";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PredictionListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_api_v1_predictions__prediction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prediction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
