"""add run, model_artifact, job tables

Revision ID: 59d3bffe52aa
Revises: c303dca66f31
Create Date: 2026-08-08 20:15:11.076782

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59d3bffe52aa"
down_revision: str | None = "c303dca66f31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("dataset_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("best_model_id", sa.String(), nullable=True),
        sa.Column("chosen_threshold", sa.Float(), nullable=True),
        sa.Column("risk_tier_bounds", sa.JSON(), nullable=True),
        sa.Column("global_importance", sa.JSON(), nullable=True),
        sa.Column("calibration_curve", sa.JSON(), nullable=True),
        sa.Column("segment_artifact_path", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index(
            "ix_run_dataset_id_created_at", ["dataset_id", "created_at"], unique=False
        )

    op.create_table(
        "job",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_artifact",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("algorithm", sa.String(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("artifact_path", sa.String(), nullable=False),
        sa.Column("explainer_path", sa.String(), nullable=True),
        sa.Column("feature_group_map", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("is_best", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_artifact")
    op.drop_table("job")
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index("ix_run_dataset_id_created_at")

    op.drop_table("run")
    # ### end Alembic commands ###
